[project]
name = "pycarrotquant"
version = "0.0.0"
description = "Carrot Quant IDE Backend"
requires-python = ">=3.14"
dependencies = [
    "apscheduler==3.11.2",
    "fastapi==0.128.0",
    "loguru==0.7.3",
    "pydantic-settings==2.12.0",
    "uvicorn==0.40.0",
]
